enhancement: ["feature/*", "feat/*"]
bug: ["fix/*", "bug/*"]
documentation: ["doc/*", "documentation/*"]
workflow: ["workflow/*", "ci/*"]
refactor: ["refactor/*", "improve/*"]
release: ["release/*", "version/*"]
