version: "3"

services:
  brand-microservices:
    image: fsfe/pipenv:bitnami-3.8
    working_dir: /app
    volumes:
      - .:/app
    container_name: brand-microservices
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: pipenv install && pipenv run start

  postgres:
    image: postgres:13.5
    env_file:
      - .env
    ports:
      - "5432:5432"
