version: "3.7"

services:
  brand_api:
    depends_on:
      - brand_db
    ports:
      - "8000:8000"
    build:
      dockerfile: ./apis/brand_api/Dockerfile
      context: .
    volumes:
      - ./apis/brand_api:/home/user/apis/brand_api
      - ./common:/home/user/common

  brand_db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./psql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "brand_db"]
      interval: 10s
      timeout: 60s
      retries: 3

volumes:
  psql_db:
