version: "3.7"

name: brand_microservices

services:
  brand_api:
    container_name: brand_api
    depends_on:
      brand_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    build:
      dockerfile: ./apis/brand_api/Dockerfile
      context: .
    volumes:
      - ./apis/brand_api:/home/user/apis/brand_api
      - ./common:/home/user/common
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=10080
      - ALGORITHM=HS256
      - JWT_SECRET_KEY=chaveSecreta2!
      - JWT_REFRESH_SECRET_KEY=frescaChaveSecreta2!

  brand_db:
    container_name: brand_db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./psql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brand_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  psql_db:
