version: "3.7"

services:
  unit:
    build:
      context: ..
      dockerfile: apis/brand_api/Dockerfile
      target: test
    volumes:
      - ../apis/brand_api:/home/user/apis/brand_api

  integration:
    depends_on:
      brand_db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: apis/brand_api/Dockerfile
      target: test
    volumes:
      - ../apis/brand_api:/home/user/apis/brand_api

  brand_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brand_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
