version: "3"
services:
  brand-microservices:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/brand-api
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./psql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brand_db
