"""update_user_foreign_keys

Revision ID: 0006
Revises: 0005
Create Date: 2023-03-11 10:08:33.630296

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("users_id_deleted_by", "users", "users", ["deleted_by_id"], ["id"])
    op.create_foreign_key("users_id_updated_by", "users", "users", ["updated_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_id_updated_by", "users", type_="foreignkey")
    op.drop_constraint("users_id_deleted_by", "users", type_="foreignkey")
    # ### end Alembic commands ###
