name: brand_microservices_ci

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3

      - name: Run tests
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
        run: make citest
