name: brand_cd

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  brand_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Write the version number to myproject
      # from the tag of current branch
      - name: Edit Toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "myproject.toml"
          key: "tool.poetry.version"
          value: "$GITHUB_REF_NAME"

      # Deploy to VPS using SSH
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/.git/, /.github/, /apis/brand_api/tests/, /brand_microservices.drawio, /.env, /traefik-public-certificates/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            pwd
            ls -la
            cd brand
            make up-prod
